### PR TITLE
Match recipient in addition to subject, body and sender

### PR DESCRIPTION
**Pull request by Devristo**
Thanks for this very nice Behat extension. For my own tests I needed to match the recipient of the mail. See this PR with my changes. Do whatever you see fit with this PR ;)

### CODE REVIEW

**Comment by rpkamp** [comment]
CircleCI wasn't set up to test PRs, so I've changed that and will close and re-open this PR to trigger the build :slightly_smiling_face:

**Comment by rpkamp** [comment]
Tests are failing:

```
/home/circleci/repo/src/Context/MailhogContext.php:46	The method iShouldSeeAnEmailWithSubjectAndBodyFromTo() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.
```
I wouldn't mind increasing this value a bit in `phpmd.xml`, to maybe 15. I mean, there is a lot of logic, but it's not all that complicated.

Would you be willing to change that in this PR, or do you want me to (in a separate PR)?

```
/home/circleci/repo/src/Context/MailhogContext.php:50	Avoid variables with short names like $to. Configured minimum length is 3.
```

Could you rename `$to` to `$recipient`? That's probably a nicer name anyway :+1:

**Comment by Devristo** [comment]
Done!  See the last changes.

**Comment by rpkamp** [comment]
Awesome! Thanks :slightly_smiling_face:

**Comment by Devristo** [comment]
Thank you 😁

**Pull request merged**
